### ISSUE TITLE
5.16 versions not using Wayland

### ISSUE THREAD

**Issue by gnarlsnishi** [probonopd/Zoom.AppImage#10]
Hello and thank you for maintaining this repo.

I am using your AppImage on an Ubuntu 22.04 system, running Gnome on Wayland. Version 5.14.7 of the AppImage ran natively on Wayland, however 5.16.0 and 5.16.2 both revert to using XWayland. Running any of the three versions from the terminal outputs this warning message:

`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread`

My .profile contains the line `export QT_QPA_PLATFORM=wayland`.

Any help troubleshooting would be greatly appreciated! :)

**Comment by probonopd** [comment]
8Wayland breaks so many things](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277) that I think I don't want to invest any time into it. If someone sends a pull request to fix this, I'm happy to merge it though, if it doesn't break things on Xorg.
