### ISSUE TITLE
Old release

### ISSUE THREAD

**Issue by aliguorilgnd** [probonopd/Zoom.AppImage#12]
Hello,

your latest release is from Jan 21 Iast pipeline is from 3 months ago. Is the project still up?

**Comment by probonopd** [comment]
Last run was 3 months ago indeed, I can't remember that I changed anything. Strange...

**Comment by herod2k** [comment]
Any update on this?

**Comment by probonopd** [comment]
Triggered a manual run. Let's see if the cron job springs back to life.
