### ISSUE TITLE
How do you run this appimage

### ISSUE THREAD

**Issue by AquisIgnisium** [probonopd/Zoom.AppImage#4]
Please help, im on elementry os latest

**Comment by probonopd** [comment]
Like every other AppImage.
How did you try to run it?
What is happening then?

**Comment by Dev-MarS** [comment]
Hey @AquisIgnisium 
use this launcher to conveniently install Appimages: https://github.com/TheAssassin/AppImageLauncher 

I'm also using eos 5.1.7 hera.

**Comment by AquisIgnisium** [comment]
Sorry about that, i was a new linux user and didnt know anything hahaha
