### ISSUE TITLE
A new way to update this and many more AppImages

### ISSUE THREAD

**Issue by ivan-hc** [probonopd/Zoom.AppImage#7]
Hi, I'm the developer of [AppMan](https://github.com/ivan-hc/AppMan) and I've wrote a new script-based Application Manager named "AM". Each program can update itself thanks to a script placed in /opt/$PROGRAM that checks for updates.

Each program of the repository can be installed/removed  with or without "AM". For example, zoom:
- With AM use the command `sudo am -i zoom` or `sudo am install zoom`
- Without AM, just download the script from [here](https://github.com/ivan-hc/AM-application-manager/blob/main/programs/x86_64/zoom), made it executable and run `sudo ./zoom`

To test if the AppImage is updatable, edit the /opt/zoom/version file (without root privileges), and launch the command:

`/opt/zoom/AM-updater`

the "AM-updater" script will not recognize the version, so it will download again the AppImage and it will replace the version in /opt/zoom/version.

Using AM you can just run the command (without "sudo"):

`am -u` or `am update`, depending on your habit if you are using PacMan / APT / DNF.

There are a lot of AppImages and other standalone programs on this repository.

I invite you to take a look at my NEW repository:

#### https://github.com/ivan-hc/AM-application-manager

PS: I already know your idea about centralized repositories, but I hope you can draw inspiration from here to solve the problem of too many non-updatable AppImage spread on the web. Hope you enjoy the idea.

**Comment by probonopd** [comment]
Thanks @ivan-hc. https://github.com/AppImageCommunity/awesome-appimage/ would be a better place to add this.
